---
- name: first playbook
  hosts: dev
  become: True
  tasks:
    - name: install python pip
      yum:
        name: python-pip
        state: present
    - name: start the container
      docker_container:
        name: tomcat
        image: "tomcat:0.0.3"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
